/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokokarunia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mei sinta
 */
public class menuPemilik extends javax.swing.JFrame {

    /**
     * Creates new form menuPemilik
     */
    private koneksi db = new koneksi();
    Statement st;
    ResultSet rs;
    String idBarang;
    String idSupplier;
    public menuPemilik() {
        initComponents();
        setLocationRelativeTo(this);
        idbrg.setVisible(false);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOME = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        KASIR = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBeli = new javax.swing.JTable();
        brgid = new javax.swing.JTextField();
        jml = new javax.swing.JTextField();
        hrg = new javax.swing.JTextField();
        comboBarang = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        konsumen = new javax.swing.JTextField();
        alamatKonsumen = new javax.swing.JTextField();
        teleponkonsumen = new javax.swing.JTextField();
        konsumenID = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        tglsekarang = new javax.swing.JLabel();
        BARANG = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jmlbarang = new javax.swing.JTextField();
        hrgjual = new javax.swing.JTextField();
        hrgbeli = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        namabarang = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        idbrg = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ud = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        telp = new javax.swing.JTextField();
        supp = new javax.swing.JLabel();
        LAPORAN = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        HOMEKASIR = new javax.swing.JPanel();
        HOME1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        HOME.setBackground(new java.awt.Color(0, 153, 153));
        HOME.setMinimumSize(new java.awt.Dimension(1280, 720));
        HOME.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(415, 75));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TOKO KARUNIA JAYA");

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("INPUT BARANG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("LAPORAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HOMELayout = new javax.swing.GroupLayout(HOME);
        HOME.setLayout(HOMELayout);
        HOMELayout.setHorizontalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(HOMELayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        HOMELayout.setVerticalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMELayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218)
                .addGroup(HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        getContentPane().add(HOME, "card2");

        KASIR.setBackground(new java.awt.Color(0, 153, 153));
        KASIR.setMinimumSize(new java.awt.Dimension(1280, 720));

        tabelBeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBeli);

        comboBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBarangItemStateChanged(evt);
            }
        });
        comboBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBarangActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("HITUNG");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));

        total.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        total.setText("0");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Rp.");

        jLabel9.setText("BAYAR");

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("SELESAIKAN PEMBAYARAN");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addComponent(bayar)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(58, 58, 58))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(61, 61, 61))
        );

        jLabel2.setText("ID BARANG");

        jLabel3.setText("HARGA SATUAN");

        jLabel5.setText("NAMA BARANG");

        jLabel6.setText("JUMLAH BELI");

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(855, 75));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("KASIR TOKO KARUNIA JAYA");

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("KEMBALI");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 819, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jLabel22.setText("KONSUMEN");

        jLabel23.setText("ALAMAT");

        jLabel24.setText("NO TELEPON");

        konsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsumenActionPerformed(evt);
            }
        });

        alamatKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatKonsumenActionPerformed(evt);
            }
        });

        konsumenID.setText("jLabel4");

        data.setText("jLabel4");

        tglsekarang.setText("jLabel4");

        javax.swing.GroupLayout KASIRLayout = new javax.swing.GroupLayout(KASIR);
        KASIR.setLayout(KASIRLayout);
        KASIRLayout.setHorizontalGroup(
            KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createSequentialGroup()
                .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KASIRLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teleponkonsumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(KASIRLayout.createSequentialGroup()
                                    .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(KASIRLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(41, 41, 41)
                                    .addComponent(brgid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel24)
                                .addComponent(jLabel23)
                                .addComponent(jLabel22)
                                .addGroup(KASIRLayout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(alamatKonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(konsumen))))))
                    .addGroup(KASIRLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jButton5))
                    .addGroup(KASIRLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(data)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(KASIRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KASIRLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(konsumenID)
                        .addGap(618, 618, 618))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tglsekarang)
                .addGap(281, 281, 281))
        );
        KASIRLayout.setVerticalGroup(
            KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KASIRLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglsekarang)
                .addGap(21, 21, 21)
                .addComponent(konsumenID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KASIRLayout.createSequentialGroup()
                        .addComponent(data)
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(konsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(alamatKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(teleponkonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(brgid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(KASIR, "card3");

        BARANG.setBackground(new java.awt.Color(0, 153, 153));
        BARANG.setMinimumSize(new java.awt.Dimension(1280, 720));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarang);

        jLabel17.setText("HARGA BELI");

        jLabel18.setText("JUMLAH BARANG");

        jLabel19.setText("NAMA BARANG");

        jLabel20.setText("HARGA JUAL");

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(855, 75));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setText("INPUT DATA BARANG");

        jButton10.setBackground(new java.awt.Color(204, 0, 0));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("KEMBALI");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        simpan.setBackground(new java.awt.Color(0, 153, 51));
        simpan.setForeground(new java.awt.Color(0, 0, 0));
        simpan.setText("SIMPAN");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(153, 0, 0));
        hapus.setForeground(new java.awt.Color(0, 0, 0));
        hapus.setText("HAPUS");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        edit.setBackground(new java.awt.Color(204, 204, 0));
        edit.setForeground(new java.awt.Color(0, 0, 0));
        edit.setText("EDIT");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        jButton8.setText("CARI");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        idbrg.setText("jLabel14");

        jLabel14.setText("NAMA UD");

        jLabel15.setText("ALAMAT");

        jLabel16.setText("NO TELEPON");

        supp.setText("jLabel22");

        javax.swing.GroupLayout BARANGLayout = new javax.swing.GroupLayout(BARANG);
        BARANG.setLayout(BARANGLayout);
        BARANGLayout.setHorizontalGroup(
            BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(BARANGLayout.createSequentialGroup()
                .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BARANGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(BARANGLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BARANGLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(58, 58, 58)
                                .addComponent(ud, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(BARANGLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hrgjual, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BARANGLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hrgbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jmlbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(BARANGLayout.createSequentialGroup()
                                    .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(namabarang)
                                        .addComponent(telp)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BARANGLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButton8))
                            .addGroup(BARANGLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 308, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(BARANGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idbrg)
                .addGap(326, 326, 326)
                .addComponent(supp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BARANGLayout.setVerticalGroup(
            BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BARANGLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BARANGLayout.createSequentialGroup()
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idbrg)
                            .addComponent(supp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)))
                    .addGroup(BARANGLayout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jmlbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrgbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrgjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        getContentPane().add(BARANG, "card3");

        LAPORAN.setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("LAPORAN TOKO KARUNIA JAYA");

        jButton13.setBackground(new java.awt.Color(153, 0, 0));
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("KEMBALI");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton14.setBackground(new java.awt.Color(255, 51, 204));
        jButton14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("LAPORAN PENJUALAN");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 51, 204));
        jButton15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("LAPORAN BARANG");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LAPORANLayout = new javax.swing.GroupLayout(LAPORAN);
        LAPORAN.setLayout(LAPORANLayout);
        LAPORANLayout.setHorizontalGroup(
            LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAPORANLayout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(535, 535, 535))
        );
        LAPORANLayout.setVerticalGroup(
            LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAPORANLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        getContentPane().add(LAPORAN, "card5");

        HOMEKASIR.setMinimumSize(new java.awt.Dimension(1280, 720));

        HOME1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel6.setBackground(new java.awt.Color(0, 102, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(415, 75));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("TOKO KARUNIA JAYA");

        jButton16.setBackground(new java.awt.Color(153, 0, 0));
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("LOGOUT");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        transaksi.setBackground(new java.awt.Color(0, 0, 204));
        transaksi.setForeground(new java.awt.Color(0, 0, 0));
        transaksi.setText("TRANSAKSI");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HOME1Layout = new javax.swing.GroupLayout(HOME1);
        HOME1.setLayout(HOME1Layout);
        HOME1Layout.setHorizontalGroup(
            HOME1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(HOME1Layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(575, Short.MAX_VALUE))
        );
        HOME1Layout.setVerticalGroup(
            HOME1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOME1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HOMEKASIRLayout = new javax.swing.GroupLayout(HOMEKASIR);
        HOMEKASIR.setLayout(HOMEKASIRLayout);
        HOMEKASIRLayout.setHorizontalGroup(
            HOMEKASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HOMEKASIRLayout.setVerticalGroup(
            HOMEKASIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(HOMEKASIR, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBarangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(false);
        HOMEKASIR.setVisible(false);
        LAPORAN.setVisible(false);
        KASIR.setVisible(false);
        BARANG.setVisible(true);
        viewDataBarang();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(false);
        HOMEKASIR.setVisible(false);
        LAPORAN.setVisible(true);
        KASIR.setVisible(false);
        BARANG.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(false);
        HOMEKASIR.setVisible(false);
        LAPORAN.setVisible(false);
        KASIR.setVisible(true);
        BARANG.setVisible(false);
        viewDataPembelian();
        brgid.setEditable(false);
        hrg.setEditable(false);
        db.dbConnection();
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "SELECT * from barang";
           ResultSet res   = stat.executeQuery(sql);
           comboBarang.removeAllItems();
           comboBarang.addItem("-- Pilih Barang --");
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                comboBarang.addItem(res.getString("nama"));
            }
      }catch(SQLException err){}
    }//GEN-LAST:event_transaksiActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login login = new login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login login = new login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(false);
        HOMEKASIR.setVisible(true);
        LAPORAN.setVisible(false);
        KASIR.setVisible(false);
        BARANG.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(true);
        HOMEKASIR.setVisible(false);
        LAPORAN.setVisible(false);
        KASIR.setVisible(false);
        BARANG.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        HOME.setVisible(true);
        HOMEKASIR.setVisible(false);
        LAPORAN.setVisible(false);
        KASIR.setVisible(false);
        BARANG.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
        String namaBarang = namabarang.getText();
        String jmlBarang = jmlbarang.getText();
        String hargabeli = hrgbeli.getText();
        String hargajual = hrgjual.getText();
        int idSupp = Integer.parseInt(supp.getText()) + 1;
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Data Sudah Benar ?", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlKonsumen="insert into barang values(NULL,'"+namaBarang+"','"+jmlBarang+"',"
                + "'"+hargabeli+"','"+hargajual+"','"+String.valueOf(idSupp)+"')";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlKonsumen);
                String sqlSupp="insert into supplier values(NULL,'"+ud.getText()+"','"+alamat.getText()+"',"
                + "'"+telp.getText()+"')";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlSupp);
                namabarang.setText("");
                jmlbarang.setText("");
                hrgbeli.setText("");
                hrgjual.setText("");
                ud.setText("");
                alamat.setText("");
                telp.setText("");
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Masukkan!!");
                viewDataBarang();   

            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int baris = tblBarang.getSelectedRow();
        String kolom1 = tblBarang.getValueAt(baris, 0).toString();
        String kolom2 = tblBarang.getValueAt(baris, 1).toString();
        String kolom3 = tblBarang.getValueAt(baris, 2).toString();
        String kolom4 = tblBarang.getValueAt(baris, 3).toString();
        String kolom5 = tblBarang.getValueAt(baris, 4).toString();
        
        db.dbConnection();


     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stati =  db.getConnection().createStatement();
           String sqli        = "Select * from barang WHERE id_barang="+kolom1;
           ResultSet reso   = stati.executeQuery(sqli);
           while(reso.next()){
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from supplier WHERE id_supplier="+reso.getString("id_supplier");
           ResultSet res   = stat.executeQuery(sql);
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                ud.setText(res.getString("nama"));
                alamat.setText(res.getString("alamat"));
                telp.setText(res.getString("no_telp"));
                supp.setText(res.getString("id_supplier"));

            } 
           }
           
      }catch(SQLException err){}

        
        idbrg.setText(kolom1);
        namabarang.setText(kolom2);
        jmlbarang.setText(kolom3);
        hrgbeli.setText(kolom4);
        hrgjual.setText(kolom5);
        simpan.setEnabled(false);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Mau menghapus Data ini", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlHapusPembelian="DELETE FROM barang WHERE id_barang = "+idbrg.getText();
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlHapusPembelian);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus !!");
                viewDataBarang();
                namabarang.setText("");
                jmlbarang.setText("");
                hrgbeli.setText("");
                hrgjual.setText("");
                ud.setText("");
                alamat.setText("");
                telp.setText("");
                simpan.setEnabled(true);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        String namaBarang = namabarang.getText();
        String jmlBarang = jmlbarang.getText();
        String hargabeli = hrgbeli.getText();
        String hargajual = hrgjual.getText();
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Data Sudah Benar ?", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlKonsumen="UPDATE barang SET nama='"+namaBarang+"',stok='"+jmlBarang+"',"
                        + "harga_awal='"+hargabeli+"',harga_jual='"+hargajual+"' WHERE id_barang='"+idbrg.getText()+"'";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlKonsumen);
                String sqlSupplier="UPDATE supplier SET nama='"+ud.getText()+"',alamat='"+alamat.getText()+"',"
                        + "no_telp='"+telp.getText()+"' WHERE id_supplier='"+supp.getText()+"'";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlSupplier);
                namabarang.setText("");
                jmlbarang.setText("");
                hrgbeli.setText("");
                hrgjual.setText("");
                ud.setText("");
                alamat.setText("");
                telp.setText("");
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Update!!");
                simpan.setEnabled(true);
                viewDataBarang();
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_editMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void alamatKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatKonsumenActionPerformed

    private void comboBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBarangItemStateChanged
        // TODO add your handling code here:
        String data1 = (String) comboBarang.getSelectedItem();
        if(data1=="-- Pilih Makanan --"){
            brgid.setText("");
            hrg.setText("");
        }
        data.setText(data1);
        db.dbConnection();
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from barang where nama='"+data1+"'";
           ResultSet res   = stat.executeQuery(sql);
           while(res.next ()){
                brgid.setText(res.getString("id_barang"));
                hrg.setText(res.getString("harga_jual"));
            }
      }catch(SQLException err){}
    }//GEN-LAST:event_comboBarangItemStateChanged

    private void konsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konsumenActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int harga = Integer.parseInt(hrg.getText());
        int jmlpesan = Integer.parseInt(jml.getText());
        int jumlah = harga*jmlpesan;
        total.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        int ttl = Integer.parseInt(total.getText());
        int byr = Integer.parseInt(bayar.getText());
        int idkons = Integer.parseInt(konsumenID.getText());
        String namabarang = data.getText();
        String harga = hrg.getText();
        String jumlah = jml.getText();
        String totalbelanja = total.getText();
        String tglskrg = tglsekarang.getText();
        int idKonsum = idkons +1;
        int kembali = byr-ttl;
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ?", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlKonsumen="INSERT INTO pembelian VALUES(NULL,'"+namabarang+"','"+jumlah+"',"
                + "'"+harga+"','"+totalbelanja+"','"+tglskrg+"','"+String.valueOf(idKonsum)+"')";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlKonsumen);
                String sqlKons="INSERT INTO konsumen VALUES(NULL,'"+konsumen.getText()+"','"+alamatKonsumen.getText()+"',"
                + "'"+teleponkonsumen.getText()+"')";
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlKons);
                JOptionPane.showMessageDialog(null, "Transaksi Berhasil, Kembalian Sebesar Rp. "+kembali);
                viewDataPembelian();
            }catch(Exception e){
                    System.out.print(e);
            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        String user = "root";
        String pwd = "";
        String url = "jdbc:mysql://localhost:3306/tokokarunia";
        HashMap param = new HashMap();
        JasperReport JasRep;
        JasperPrint JasPri;
        JasperDesign JasDes;
        
        try{
            Connection conn = DriverManager.getConnection(url,user,pwd);
            String path="src/Report/penjualan.jasper"; 
            JasperPrint cetak = JasperFillManager.fillReport(path,param,conn);
            JasperViewer viewer = new JasperViewer(cetak,false);
            JasperViewer.viewReport(cetak,false);
            viewer.setFitPageZoomRatio();
            viewer.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuPemilik.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuPemilik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        String user = "root";
        String pwd = "";
        String url = "jdbc:mysql://localhost:3306/tokokarunia";
        HashMap param = new HashMap();
        JasperReport JasRep;
        JasperPrint JasPri;
        JasperDesign JasDes;
        
        try{
            Connection conn = DriverManager.getConnection(url,user,pwd);
            String path="src/Report/barang.jasper"; 
            JasperPrint cetak = JasperFillManager.fillReport(path,param,conn);
            JasperViewer viewer = new JasperViewer(cetak,false);
            JasperViewer.viewReport(cetak,false);
            viewer.setFitPageZoomRatio();
            viewer.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuPemilik.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuPemilik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             tblBarang.setModel(model);
             model.addColumn("ID");
             model.addColumn("NAMA BARANG");
             model.addColumn("JUMLAH BARANG");
             model.addColumn("HARGA BELI");
             model.addColumn("HARGA JUAL");


     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "SELECT * FROM barang WHERE nama LIKE '%"+cari.getText()+"'\n" +
                               "OR stok LIKE '%"+cari.getText()+"'OR harga_awal "
                   + "LIKE '%"+cari.getText()+"' OR harga_jual LIKE '%"+cari.getText()+"'";
           ResultSet res   = stat.executeQuery(sql);
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = res.getString("id_barang");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("stok");
                obj[3] = res.getString("harga_awal");
                obj[4] = res.getString("harga_jual");
                model.addRow(obj);
            }
      }catch(SQLException err){}
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPemilik().setVisible(true);
            }
        });
    }
    
    void viewDataBarang(){
        db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             tblBarang.setModel(model);
             model.addColumn("ID");
             model.addColumn("NAMA BARANG");
             model.addColumn("JUMLAH BARANG");
             model.addColumn("HARGA BELI");
             model.addColumn("HARGA JUAL");


     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from barang";
           ResultSet res   = stat.executeQuery(sql);
           Statement stati =  db.getConnection().createStatement();
           String sqli="SELECT id_supplier FROM supplier ORDER BY id_supplier DESC LIMIT 1;\n" +"";
           ResultSet reso   = stati.executeQuery(sqli);
            while(reso.next()){
             supp.setText(reso.getString("id_supplier"));
             supp.setVisible(false);
            }
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = res.getString("id_barang");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("stok");
                obj[3] = res.getString("harga_awal");
                obj[4] = res.getString("harga_jual");
                model.addRow(obj);
            }
      }catch(SQLException err){}
    }
    void viewDataPembelian(){
        db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
        tabelBeli.setModel(model);
        model.addColumn("ID");
        model.addColumn("NAMA BARANG");
        model.addColumn("JUMLAH BARANG");
        model.addColumn("HARGA");
        model.addColumn("TOTAL");
        model.addColumn("TANGGAL");
        Date skrg = new Date();
        SimpleDateFormat wkt = new SimpleDateFormat("dd-MM-yyyy");
        tglsekarang.setText(wkt.format(skrg));
        tglsekarang.setVisible(false);

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from pembelian";
           ResultSet res   = stat.executeQuery(sql);
           Statement stati =  db.getConnection().createStatement();
           String sqli="SELECT * FROM konsumen ORDER BY id_konsumen DESC LIMIT 1;\n" +"";
           ResultSet reso   = stati.executeQuery(sqli);;
            while(reso.next()){
             konsumenID.setText(reso.getString("id_konsumen"));
            }
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[6];
                obj[0] = res.getString("id_pembelian");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("jumlah");
                obj[3] = res.getString("harga");
                obj[4] = res.getString("total");
                obj[5] = res.getString("tanggal");

                model.addRow(obj);
            }
      }catch(SQLException err){}
    }
    
    void tampil(){
        if(UserSession.getType()=="Pemilik"){
            HOME.setVisible(true);
            HOMEKASIR.setVisible(false);
            LAPORAN.setVisible(false);
            KASIR.setVisible(false);
            BARANG.setVisible(false);
        }else{
            HOME.setVisible(false);
            HOMEKASIR.setVisible(true);
            LAPORAN.setVisible(false);
            KASIR.setVisible(false);
            BARANG.setVisible(false);
            tglsekarang.setVisible(false);
            data.setVisible(false);
            konsumenID.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BARANG;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel HOME1;
    private javax.swing.JPanel HOMEKASIR;
    private javax.swing.JPanel KASIR;
    private javax.swing.JPanel LAPORAN;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField alamatKonsumen;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField brgid;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> comboBarang;
    private javax.swing.JLabel data;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hrg;
    private javax.swing.JTextField hrgbeli;
    private javax.swing.JTextField hrgjual;
    private javax.swing.JLabel idbrg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jml;
    private javax.swing.JTextField jmlbarang;
    private javax.swing.JTextField konsumen;
    private javax.swing.JLabel konsumenID;
    private javax.swing.JTextField namabarang;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel supp;
    private javax.swing.JTable tabelBeli;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField teleponkonsumen;
    private javax.swing.JTextField telp;
    private javax.swing.JLabel tglsekarang;
    private javax.swing.JLabel total;
    private javax.swing.JButton transaksi;
    private javax.swing.JTextField ud;
    // End of variables declaration//GEN-END:variables
}
